$(document).ready(function(){

	$("#id_comeEntreComidas_0").click(function(){
	   $('#condicion1').removeClass("noDisplayDiv");
	});
	$("#id_comeEntreComidas_1").click(function(){
	  $('#condicion1').addClass("noDisplayDiv");
	});
	$("#id_modificadoAlimentacionReciente_0").click(function(){
	   $('#condicion2').removeClass("noDisplayDiv");
	   $('#condicion3').removeClass("noDisplayDiv");
	});
	$("#id_modificadoAlimentacionReciente_1").click(function(){
	  $('#condicion2').addClass("noDisplayDiv");
	  $('#condicion3').addClass("noDisplayDiv");
	});
	$("#id_esAlergicoIntolerante_0").click(function(){
	   $('#condicion4').removeClass("noDisplayDiv");
	});
	$("#id_esAlergicoIntolerante_1").click(function(){
	  $('#condicion4').addClass("noDisplayDiv");
	});
	$("#id_suplementoAlimenticio_0").click(function(){
	   $('#condicion5').removeClass("noDisplayDiv");
	   $('#condicion6').removeClass("noDisplayDiv");
	});
	$("#id_suplementoAlimenticio_1").click(function(){
	  $('#condicion5').addClass("noDisplayDiv");
      $('#condicion6').addClass("noDisplayDiv");
	});
	$("#id_consumoVariaEmocion_0").click(function(){
	   $('#condicion7').removeClass("noDisplayDiv");
	});
	$("#id_consumoVariaEmocion_1").click(function(){
	  $('#condicion7').addClass("noDisplayDiv");
	});
	$("#id_tieneDieta_0").click(function(){
	   $('#condicion8').removeClass("noDisplayDiv");
	   $('#condicion9').removeClass("noDisplayDiv");
	});
	$("#id_tieneDieta_1").click(function(){
	  $('#condicion8').addClass("noDisplayDiv");
	  $('#condicion9').addClass("noDisplayDiv");
	});

	$("#id_comeEntreComidas_1").click();
	$("#id_modificadoAlimentacionReciente_1").click();
	$("#id_esAlergicoIntolerante_1").click();
	$("#id_suplementoAlimenticio_1").click();
	$("#id_consumoVariaEmocion_1").click();
	$("#id_tieneDieta_1").click();
	$("#id_salComidas_1").click();
	
});